import { GOD_MODE_SYSTEM_PROMPT } from './god-mode';
import { RERANKER_SYSTEM_PROMPT } from './reranker';
import { EXTRACTION_SYSTEM_PROMPT, EXTRACTION_USER_PREFIX } from './extraction';
import { ENRICHMENT_WEB_SEARCH_PROMPT } from './enrichment';
import { CLASSIFICATION_SYSTEM_PROMPT } from './classification';
import { SESSION_TITLE_PROMPT } from './session-title';
import { IMPORT_COLUMN_MAPPING_PROMPT } from './import-mapping';
import {
  TRANSCRIPT_EXTRACTION_SYSTEM_PROMPT,
  TRANSCRIPT_SUMMARY_SYSTEM_PROMPT,
} from './transcript-extraction';

export const LLM_PROMPTS = {
  GOD_MODE_SYSTEM: GOD_MODE_SYSTEM_PROMPT,
  RERANKER_SYSTEM: RERANKER_SYSTEM_PROMPT,
  EXTRACTION_SYSTEM: EXTRACTION_SYSTEM_PROMPT,
  EXTRACTION_USER_PREFIX,
  ENRICHMENT_SEARCH: ENRICHMENT_WEB_SEARCH_PROMPT,
  CLASSIFICATION_SYSTEM: CLASSIFICATION_SYSTEM_PROMPT,
  SESSION_TITLE: SESSION_TITLE_PROMPT,
  IMPORT_MAPPING: IMPORT_COLUMN_MAPPING_PROMPT,
  TRANSCRIPT_EXTRACTION: TRANSCRIPT_EXTRACTION_SYSTEM_PROMPT,
  TRANSCRIPT_SUMMARY: TRANSCRIPT_SUMMARY_SYSTEM_PROMPT,
};
